insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Yeast - Fresh, Fleischman', 86.34);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Whmis - Spray Bottle Trigger', 608.83);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Eel - Smoked', 398.31);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ham - Smoked, Bone - In', 740.46);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cheese - Pied De Vents', 772.82);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Fudge - Cream Fudge', 578.84);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Beef - Salted', 635.01);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Radish - Pickled', 190.78);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Browning Caramel Glace', 383.76);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Watercress', 444.02);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ecolab - Balanced Fusion', 76.65);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Longos - Lasagna Veg', 426.4);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cheese Cloth No 100', 176.08);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Island Oasis - Raspberry', 979.18);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Broom And Brush Rack Black', 347.98);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Flour - Bran, Red', 156.16);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Spring Roll Veg Mini', 768.91);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pepper - Sorrano', 656.48);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Vinegar - Balsamic, White', 931.59);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Plate Pie Foil', 776.76);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Yogurt - Peach, 175 Gr', 845.71);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pepper - Julienne, Frozen', 485.42);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Puff Pastry - Slab', 343.93);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lentils - Red, Dry', 32.82);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bread - Multigrain Oval', 252.73);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Island Oasis - Pina Colada', 674.43);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mushroom - Porcini, Dry', 257.73);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Leeks - Large', 788.66);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Truffle Shells - White Chocolate', 163.35);
insert into producto (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mikes Hard Lemonade', 285.44);
